---
  header_logo_url:
  header_logo_text: Worldwide Gelechiidae Species
  header_links:
    - label: Home
      link: /

    - label: Browse Catalog
      link: /otus/234102/overview

    - label: About
      link: /about
